[#ftl]
[@b.head/]
[@b.toolbar title="认定科目维护"]
    bar.addBack("${b.text("action.back")}");
[/@]
[@b.form name="settingForm" action=b.rest.save(setting) theme="list"]
    [@b.select name="setting.certificate.id" label="证书名称" required="true" style="width:300px" items=certificates?sort_by("name") empty="..."  value=setting.certificate! /]
    [@b.textfield name="setting.validMonths" label="有效月数" value=setting.validMonths! maxLength="10" required="false" style="width:150px" comment="以月为单位，不适用可以为空"/]
    [@b.radios label="学院审核" name="setting.collegeReviewRequired" value=setting.collegeReviewRequired items="1:需要所在学院审核,0:单独指定部门审核" required="true"/]
    [@b.select name="setting.auditDepart.id" label="审核部门" items=project.departments  value=setting.auditDepart! empty="..." required="false"/]
    [@b.radios label="学科专业" name="setting.special" value=setting.special items="1:面向特定学院,0:全校通用" required="true"/]
    [@b.select name="depart.id" label="适用学院" items=project.departments multiple="true"  values=setting.departs empty="..." required="false"/]
    [@b.select name="major.id" label="适用专业" items=majors multiple="true"  values=setting.majors empty="..." required="false"/]

    [@b.textfield name="setting.credits" label="学分数"  value=setting.credits  required="true"/]
    [@b.textarea name="setting.remark" label="额外说明" value=setting.remark! maxLength="200" style="width:400px" rows="4"/]
    [@b.formfoot]
        <input type="hidden" name="setting.config.id" value="${(setting.config.id)!}"/>
        <input type="hidden" name="config.id" value="${(setting.config.id)!}"/>
        [@b.submit value="action.submit"/]
        [@b.reset/]
    [/@]
[/@]
[#list 1..5 as i]<br>[/#list]
[@b.foot/]
