[@b.grid items=applies var="apply" theme="mini"]
    [@b.row]
        [@b.col property="certificate.name" title="证书" width="40%"/]
        [@b.col property="subjects" title="证书内课程"/]
        [@b.col property="acquiredIn" title="获得年月" width="10%"]${(apply.acquiredIn?string("yyyy-MM"))!"--"}[/@]
        [@b.col title="学分" property="credits" sortable="false" width="5%"/]
        [@b.col property="status" title="状态" width="9%"]${apply.status}[/@]
        [@b.col property="updatedAt" title="提交时间" width="15%"]${apply.updatedAt?string("MM-dd HH:mm")}[/@]
    [/@]
[/@]
