[#ftl]
[@b.head/]
[@b.toolbar title="能力素质课程学分认定设置"]
  bar.addBack();
[/@]
[@b.form name="configForm" action=b.rest.save(config) theme="list"]
    [@b.select name="config.eduType.id" label="培养类型" items=project.eduTypes  value=config.eduType!   required="true"/]
    [@b.select name="level.id" label="培养层次" items=project.levels  values=config.levels multiple="true" required="true"/]
    [@b.startend label="认定时间" readOnly="readOnly"  required="true"  name="config.beginAt,config.endAt" required="true" start=config.beginAt end=config.endAt format="yyyy-MM-dd HH:mm:ss" /]
    [@b.textarea name="config.notice" required="true" maxlength="1000" label="认定须知" value=(config.notice)! cols="80" rows="6"/]
    [@b.number name="config.credits" required="true" label="要求学分" value=config.credits /]
    [@b.formfoot]
      [@b.reset/]
      [@b.submit value="action.submit" /]
    [/@]
[/@]
[@b.foot/]
